version: 0.2
os: linux

files:
  - source: /
    destination: /home/ubuntu/hello-world

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
